spring.application.name=event-system

# H2 DB
spring.datasource.url=jdbc:h2:mem:eventdb;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 콘솔 화면 활성화
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console