spring.application.name=event-system

# H2 DB
spring.datasource.url=jdbc:h2:mem:eventdb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.generate-unique-name=false

#schema.sql, data.sql 무조건 실행
spring.sql.init.mode=always

# H2 콘솔 화면 활성화
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console