ALTER TABLE banquet
ADD COLUMN version BIGINT NOT NULL DEFAULT 0,
ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN created_by BIGINT,
ADD COLUMN updated_by BIGINT;